name: Django Test CI

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [main]
    pull_request:
        branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
           python-version: 3.11.7
      - name: Install requirements
        run: |
            pip install -r requirements.txt
      - name: Run tests
        run: |
            python manage.py test account/tests
